### ISSUE TITLE
Move "vignettes" message property to env variable  "KBASE" (or possible command line arg)

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/precision-feedback-pipeline#10]
Not sure about command line args with uvicorn and FastAPI. Alternatively is just using an environment variable.

```bash
export KBASE=/Users/bob/knowledge/kbase42 
uvicorn main:app etc.
```

then use `location = os.getenv("KBASE", "knowledge-base")` in the code. This will work well with cloud deployments when we add URL handling (#11) 

* In general, pipeline should only load the knowledge base at startup from a specific location (or default)
* `kbase` should point to a folder in the filesystem location, e.g. `/Users/bob/knowledge/kbase42`
* argparse and os.getenv are builtin python core library functions
* default should be a folder called knowledge-base in the current directory (this matches the repo name for the standard knowledgebase)

Notes:
* Means the code should expect and read the knowledge base files organized in the same way as the default knowledge base repo
* maybe if using command line flag, --kbase or -k for short

This supercedes #2

**Comment by icejag** [comment]
Three files are required to run the pipeline, measure.json,templates.json and causal_pathways.json. It was decided to create environment variable for each file required. The environment variables are created and deployed in heroku. Code cleanup was also done.
