### ISSUE TITLE
create variable processing for Pictoralist

### ISSUE THREAD

**Issue by zachll** [Display-Lab/precision-feedback-pipeline#107]
Pictoralist needs to receive the following variables from Esteemer for email text population via message templates:

1. Measure name
2. Recipient performance level
        = performance level as percentage with numerator and denominator, such as "90% (9/10)"
3. Comparator performance level
        = performance level as percentage such as "90%"
4. Consecutive positive gaps duration - post pilot?
5. Consecutive negative gaps duration - post pilot?
6. [here (link to measure spec)] - insert as url
7. [clinical quality dashboard (link)] - insert as url

The message library spreadsheet is the source of truth for these variables: https://docs.google.com/spreadsheets/d/1h81ZmTqMWvWDcpLIr5IFW-AAmEiqQAPB4ZtyQtY87HQ/edit#gid=439820594

**Comment by mackgalante** [comment]
From spreadsheet, for quick reference:

[Not top performer message template]
"You are not a top performer this month for the measure [measure name]. Your performance was [recipient performance level], below the top 10% peer benchmark, which was [comparator performance level] this month.                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 A case-by-case breakdown of your results are available at your [clinical quality dashboard (link)]. More information about the rationale for the measure [measure name] and how it is calculated is available [here (link to measure spec)]."

**Comment by mackgalante** [comment]
Resolved with commit https://github.com/Display-Lab/precision-feedback-pipeline/pull/113/commits/5fa3efed76b2eb1c3f3d6b127856e443d48f51b9 to pull request #113

**Comment by mackgalante** [comment]
Have left post-pilot work for another day, and documented rationale on leaving the link insertion to the MPOG team in the changelog for V 0.2.0

Closing issue as resolved for now, can re-open if needed at team review tomorrow
