### ISSUE TITLE
match comparator terms with PSDO

### ISSUE THREAD

**Issue by zachll** [Display-Lab/precision-feedback-pipeline#12]
Revise pipeline to use input message column names for comparator terms that match PSDO
For example, replace "Top_10_Average" with "peer 90th percentile benchmark"

**Comment by zachll** [comment]
Use underscores instead of spaces for all labels, like "peer_90th_percentile_benchmark"

**Comment by icejag** [comment]
The changes to column names are made with [commit](https://github.com/Display-Lab/precision-feedback-pipeline/commit/06aecdf415e4e18a63f63c9a0fd3071ddd40bfc0)
