### ISSUE TITLE
Visual display tweaks

### ISSUE THREAD

**Issue by zachll** [Display-Lab/precision-feedback-pipeline#127]
As the charts produced by Pictoralist are harmonized with the prototype slide deck, we are recognizing several minor improvements to implement:

 - bars in barcharts for comparator and recipient should touch within each month
 - limit precision of recipient performance to one decimal point (only for the text message and visual display)

**Comment by mackgalante** [comment]
Additional changes to improve pictoralist:

- [ ] Check and create local cache folder if not present
- [ ] Keep the last 20 png files, overwrite if more than 20 images cached
- [ ] Create infrastructure for setting display changes by env var and programmatically from Esteemer (goal line, timeframes for displays, message_instance_id)

**Comment by mackgalante** [comment]
Request from Anjana for making data voids graphed continuously, have started working towards that code on the display tweaks branch (linked to this issue)

**Comment by mackgalante** [comment]
Using goal hline in bar chart, seems alright. Can copy code over to line chart if we so desire.

Tweaks to bar and line charts are done, tested. Having issues with esteemer, will have to review what changes were made this morning and try rolling them back...

Not in love with the way that the bar charts have hard-coded offsets for the data labels, will not be adjusting based on the number of bars. Will try to calculate similar offset another way or just using barwidth as a unit... Should leave for post-launch
