### ISSUE TITLE
pipeline should include short message id in the output message

### ISSUE THREAD

**Issue by zachll** [Display-Lab/precision-feedback-pipeline#143]
- include the short message id from the message template in the message id in the output message

**Comment by pboisver** [comment]
Won't implement for now. All messages are usable in a single external (email) template, for MPOG process. Also, IRIs of message templates currently provide a GUID element that is usable for machined processing.

**Comment by mackgalante** [comment]
Would really like if instead we pulled through the message template name for debug use - more useful than the IRI in my opinion, see LDT issue [here](https://github.com/Display-Lab/Leakdown-Tester/issues/16)
