### ISSUE TITLE
handle missing data for current month plus recent months

### ISSUE THREAD

**Issue by zachll** [Display-Lab/precision-feedback-pipeline#145]
Motivation:
 - we don't want to give precision feedback if no data is available from the most recent month
 - if  provider goes on leave for a few months, how with will the pipeline handle this missing data?
 - probably we could pause the delivery of precision feedback until they have data again for the current month

**Comment by mackgalante** [comment]
Strategy wise, best to make this check happen across their performance dataframe and compare each measure's last month across the board with the current month from datetime, and if non match the current month we log something and stop the whole process before any further processing is done...

Realistically, probably easiest to process their data anyway and stop feedback delivery from pictoralist, where all of the data needed to make this call is already pulled. This would be wasting energy on processing data, but it's a call about if we want it to be 'optimal' or just functional for the pilot.

**Comment by zachll** [comment]
No emails are sent if no data are available in the most recent month for all measures, so this is not an issue.

**Comment by zachll** [comment]
Do more testing to see what happens with bad data. If the pipeline receives outdated data, it will present the feedback as if it is current, which is problematic.
