### ISSUE TITLE
Display tweaks III

### ISSUE THREAD

**Issue by zachll** [Display-Lab/precision-feedback-pipeline#156]
- [x] limit the precision of recipient performance in bar and line charts to zero decimal points (i.e. 89% instead of 89.0%). Text messages intended for and rendered in the email template should be the decimal point of precision. (Values included in the output message outside of the text message, if any, can also be one decimal point of precision; no such properties at present). 

 - [x]  add case count values for numerator and denominator to recipient performance in bar and line charts (all months of recipient bars, but only last three months of line chart) - looks like this is done for bar chart but not line chart
 - [x]  remove chart title above bar chart and line chart
 - [x]  remove axis labels "Performance Level" and "Time" from charts
 - [x]  Rotate month labels on x axis to be horizontal
 - [x]  change legend to display items in one row, horizontally, rather than a column or chart inset
 - [x]  remove border around legend
 - [x]  increase font sizes by 3 to 5 points or so
 - [x]  display of the goal line should be limited only to bar charts, not the line chart
 - [x] the environment variable that sets the amount of month for line chart is not working correctly. For instance 6 months of data graphs 12 months of data-This is a bug and need to be fixed.

**Comment by mackgalante** [comment]
- Check readme, needs format changes for github display

**Comment by mackgalante** [comment]
Legend border may be resolved by modifying frameon (bool, default true)

**Comment by zachll** [comment]
![Image](https://github.com/Display-Lab/precision-feedback-pipeline/assets/13623/92d69af4-5593-4ab8-8ec2-26f1d0c5ae8e)

The increased font size looks great for the axis labels and legend, but needs to be dialed back for the performance levels appearing in the bars

**Comment by zachll** [comment]
Based on local testing of the 156-display-tweaks-iii branch, need the following:

- [ ] move the legend to appear below the chart, centered based on the width of the chart
- [ ] remove the decimal point for the performance level percentages
- [ ] generate images with a blue background based on the background color of the existing email

**Comment by zachll** [comment]
- [ ] in the bar chart only, remove the single decimal value of performance level percentage for comparator bars
- [ ] in the bar chart only, decrease the font size of the numerator and denominator by 1 point for the recipient performance level
- [ ] in the bar chart only, increase the font size of the percentage for recipient performance by about 3 points, depending on how much space "100" takes up, and increase font size of the comparator performance percentage to match the recipient performance percentage font size
