### ISSUE TITLE
502 BAD GATEWAY error

### ISSUE THREAD

**Issue by icejag** [Display-Lab/precision-feedback-pipeline#161]
Mark Dehring from MPOG did the stress test:

StatusCode: 502, ReasonPhrase: 'Bad Gateway', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
Referrer-Policy: no-referrer
Date: Wed, 15 Nov 2023 01:59:22 GMT
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Content-Type: text/html; charset=utf-8
Content-Length: 332
}

This error is reproducible only in GCP and not in Heroku. It is random and last only for 30 seconds and corrects itself after that.
Delayed request method is not working.
HITS HIGHEST PRiORITY REQUEST is made in the ticket My Request - INC2376477  and all communication is available in the [ticket](https://michmed.service-now.com/sp?id=ticket&table=incident&sys_id=31f259d547263d140842a1cd416d43f1)

**Comment by mackgalante** [comment]
Throttling requests after 30 seconds uptime with a 30 second delay before resuming works around issue, but would not say the error is resolved, per se.

**Comment by icejag** [comment]
HITS resolution for this error: IT is on us to solve this problem.

DevOps has been able to replicate your 502 issues. When your application comes under heavy load, Google's load balancer's health check (currently set to "/" in your test.yaml and prod.yaml files) fails and returns a 502. We recommend:
- Create a separate health check endpoint that is not blocked unless the application is actually unavailable, then update test.yaml and prod.yaml to use this healthcheck endpoint
- Consider increasing your replica count in test.yaml and prod.yaml (note: the best way to tune this to experiment with different load sizes)
