### ISSUE TITLE
Mark's stress test ISSUE-3: 500 ERROR(INTERNAL SERVER ERROR)

### ISSUE THREAD

**Issue by icejag** [Display-Lab/precision-feedback-pipeline#163]
Mark Dehring from MPOG did the stress test and he got this error randomly.
StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Wed, 15 Nov 2023 01:58:25 GMT
  Server: uvicorn
  Strict-Transport-Security: max-age=63072000
  Via: 1.1 google
  Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  Content-Length: 21
  Content-Type: text/plain; charset=utf-8
}

A 500 error is an error from the application. We ran the sample data sent by Mark against local and Heroku server. We noticed that the tests passed for 60 records when the pictoralist is switched off. When the pictoralist is switched on, the pipeline threw a 500 error for some provider especially when generating bar charts.

**Comment by mackgalante** [comment]
Error as diagnosed from Provider_29:
Issue stemming from this line, 275 in pictoralist.generate_barchart()
`self.performance_data['passed_count'].iloc[-self.display_timeframe + index]`

Issue is an indexError, single positional indexer out-of-bounds


Working on a patch in linked branch, will update with progress as it moves forward
