### ISSUE TITLE
Candidate selection behavior change with multiple measures

### ISSUE THREAD

**Issue by mackgalante** [Display-Lab/precision-feedback-pipeline#168]
We currently have the pipeline selecting candidates that we don't like, for instance with Provider_29

Need to have Esteemer or somewhere else use either tweaks to the algorithm's weights or additional parameters to prevent measures from becoming selected candidates where the data is insufficient for feedback.

**Comment by icejag** [comment]
@mackgalante  Is this issue already addressed ? Can you give more information.

**Comment by mackgalante** [comment]
Apologies for leaving this open, was related to the root causes that were corrected in the pull request for #172

**Comment by mackgalante** [comment]
Closing now
