### ISSUE TITLE
Add signal/score for message recurrence in feedback message history

### ISSUE THREAD

**Issue by mackgalante** [Display-Lab/precision-feedback-pipeline#226]
Calculate a score based on characteristics of the feedback message history that contribute to surprisingness.

Given: a history of feedback messages with time_interval, type/template, measure. (All history is for a single recipient).

Okay to start with the **_recurrence_** of a specific feedback message template, characterized by **_recency_** and **_count_**.

signal detection function: TBD, signal = f(m, hist)
score function: TBD, score = g(signal)

For example:
parameters:
   m = current message
   hist = feedback message history
returns:
   count = number of messages in the last 6 months
   recency = number of intervals since the last message

   signal(b,[a, b, c, b, a, d, d, d]) == (2, 2)  score(signal) == 2/42+2
   signal(a,[a, b, c, b, a, d, d, d]) == (2, 1)   
   signal(c,[a, b, c, b, a, d, d, d]) == (1, 3)
   signal(e,[a, b, c, b, a, d, d, d]) == None

**Comment by pboisver** [comment]
We are considering creating an _annotation function_ that will accept _Information Content_ of the type **MessageHistory** and extract _Motivating Information_ of the type **MessageRecurrence**, with properties like _recency_ and _count_.

The **MessageReccurence** and its properties (moderators) would then be inputs to the _esteemer function_ which could be used by Esteemer when evaluating the _Motivation Potential_ of a candidate message.

This would roughly parallel the handling of performance-related information content (i.e. the number block) for message-related information content (i.e. the JSON history object).

**_This does not imply exactly where the _annotation function_ and the _esteemer function_ should be invoked!_**. For example, BitStomach is focused on _performance information content_; it is not clear that _message-related information content_ should be processed in BitStomach.
