### ISSUE TITLE
Allow additional non top performer messages

### ISSUE THREAD

**Issue by icejag** [Display-Lab/precision-feedback-pipeline#232]
For January  

Edited to add: Please make sure that the "Congrats" message, "top 25%" message, and MPM with zero weight for social worse are correctly part of the mpog_pilot kb branch for configuration.

1. ~~Reduce the data filtering threshold~~
2. Add a top 25% message template
3. ~~boost mpm score with 1000 for social better.~~ Reduce "social better" weight to 0
4. ~~Treat no valid message as 400 error.~~

**Comment by zachll** [comment]
Problem: A small number of providers will not have any message on which they can be congratulated for high performance. 

The above are potential solutions to consider.
