### ISSUE TITLE
Refactoring items

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/precision-feedback-pipeline#235]
### Esteemer:

- [ ] get__selected_message function refactor
- [ ] Variable names, cleanup stuff, good place to start
- [ ] Clean out variables with only one reference
- [ ] Variable renaming
- [ ] Refactor of functional blocks (some work attempted here, esteemer.ipynb)
- [ ] **Score function** needs help
- [ ] Refactor of any possible logic in logic loops
- [ ] Variable renaming
- [ ] Comments describing function of any of the code in the score func

### Thinkpudding:

- [ ] Load.py could use guiding comments, var rewrite
- [ ] thinkpudding.py needs comments to describe what it is doing
- [ ] Candidatesmasher:
- [ ] Looks like cleanup is in progress, check open branch on PFP
- [ ] Var rename, comments, the usual
- [ ] 

### Bitstomach:
Looks good!

- [ ] Var rename is complete
- [ ] Comments on what code blocks are doing would help

Once above done, refactoring of repetitive logic could be done?

**Comment by icejag** [comment]
I have checked on items that are done.

- [ ] - [ ] get__selected_message function refactor
- [x] Variable names, cleanup stuff, good place to start
- [x] Clean out variables with only one reference
- [x] Variable renaming
- [ ] Refactor of functional blocks (some work attempted here, esteemer.ipynb)
- [ ] **Score function** needs help
- [ ] Refactor of any possible logic in logic loops
- [x] Variable renaming
- [ ] Comments describing function of any of the code in the score func

### Thinkpudding:

- [x] Load.py could use guiding comments, var rewrite
- [x] thinkpudding.py needs comments to describe what it is doing
- [x] Candidatesmasher:
- [x] Looks like cleanup is in progress, check open branch on PFP
- [x] Var rename, comments, the usual
- [ ] 

### Bitstomach:
Looks good!

- [x] Var rename is complete
- [x] Comments on what code blocks are doing would help
