### ISSUE TITLE
Esteemer 2 -Update scoring algorithm to use magnitude for trends and gaps.

### ISSUE THREAD

**Issue by faridseifi** [Display-Lab/precision-feedback-pipeline#251]
### Note

- Candidates should be scored _**only**_ using the MI specified in the dispositions for that candidate. (These come from the casual pathway and/or the message template).
- Even for "social better" messages there will (I think) only be two positive comparisons, the goal comparison and the top-tiered social comparison.
- When we create instances of MI (using annotation functions) we can add the appropriate comparator and magnitude info (and monotonicity, trend length, whatever) so that esteemer will have what it needs for scoring as it goes through the **_relevant_** MI instances for a candidate

**Comment by pboisver** [comment]
Consider representing gaps and trends as counts
