### ISSUE TITLE
fix candidate List in the output to show the candidate score when esteemer 1 is used

### ISSUE THREAD

**Issue by faridseifi** [Display-Lab/precision-feedback-pipeline#264]
### Problem
The candidate list is a short representation of candidate messages that is added to the output message. It uses the candidate information in the graph to prepare the candidate representations. For candidate scores it uses the literal with relation "http://example.com/slowmo#Score" for each candidate.

Esteemer 1 right now tags each candidate with hard coded score **Literal(1)**. 

### Solution
Update the line 65 in esteemer.py                 
`self.performer_graph.add((s, URIRef('http://example.com/slowmo#Score'), Literal(1)))`
 to tag candidate with the right score.

**Comment by faridseifi** [comment]
This is done as part of commit [251 esteemer 2 update scoring algorithm to use magnitude for trends and gaps](https://github.com/Display-Lab/precision-feedback-pipeline/commit/6950c49b9d447aa51e973d61d873c881a0cb2e66)

closing

**Comment by icejag** [comment]
This bug resurfaced today even after pulling in the updated code. Please kindly check.

**Comment by pboisver** [comment]
closed by #277
