### ISSUE TITLE
selection of Top 25% message using social better when messages using social worse are available

### ISSUE THREAD

**Issue by zachll** [Display-Lab/precision-feedback-pipeline#267]
Problem:
When 2 candidates are available for one measure, such that one is a Top 25% message, and the other is an "Opportunity to improve" message, Top 25% is found to be acceptable by social better, and the other message is found to be acceptable by social worse. However, the pipeline seems not to select the Top 25% message, even when the absolute value of the gap size is larger for social better.

For example, when the recipient's performance is 95%, the 75th percentile benchmark is 92% and the 90th percentile benchmark is 96%, the pipeline will always select the "Opportunity to improve" message.

Test:
[1,"SUS04","2023-12-01",95,2,100,90,92,96,90]

### Notes

* Remember to use the current `mpog_pilot` KB configuration which include 4 CPs and 5 messages (top 10, top 25, getting worse, improving, opportunity to improve)

**Comment by icejag** [comment]
@zachll I am not able to recreate the error. Please kindly test the test case again.I guess there might be a mistake somewhere.

**Comment by icejag** [comment]
Please kindly let me know whether this is for esteemer2 or esteemer1. I am still not able to recreate this bug.
