### ISSUE TITLE
Move scoring (motivational potential) functions to a maintainable format (per CP)

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/precision-feedback-pipeline#292]
We might say they are all linear, and there is one function per causal pathway. Then we just need to look up the parameters for a linear equation.

But maybe we need to encapsulate the motivational potential function as a black box that shares no code with other functions.

Basically:

* All MI moderators are normalized to 0..1. The moderator expresses surprisingness with 1 being most surprising and 0 being unsurprising.
* History moderators (recency and count of recurrences) are also normalized as 0..1 (same surprisingness scale)
* performance motivational potential = surprisingness of MI moderators * MPM weight (per causal pathway). Probably need to re-normalize moderators to 0..1 before applying MPM
* history motivational potential = surprisingness of History moderators * MPM weight (per causal pathway). Probably still normalized; apply MPM directly.
* preferences are applied to the sum? of all motivational potential. N.B. be sure to check signs.

score = (MI*MPM + History*MPM)(1+preference)

See also #318

**Comment by faridseifi** [comment]
For example here is how trends are scored relative to gaps 

 **Effect of Motivating Information**
Social Better – Gap size 1 – Score: 0.015
Social Worse – Gap size 1 – Score: -0.009
Improving – 1 units per month – score: 0.04     
- To get social better with score of 0.04 we need gap size of 6
- To get Social worse with score of 0.04 we need gap size of 50
- Worsening need 5 unit per month(100 to 90 over 3 month)to generate score of 0.04

Worsening – 1 units per month – score: 0.008

-----------------------------------

Social Better – Gap size 10 – Score: 0.06 
Social Worse – Gap size 10 – Score: 0.0
Improving – 10 units per month – score: 0.4     
- To get social better with score of 0.4 we need gap size of 78 
- Social worse will never win. gap size of 100 gives score of 0.08
- Worsening need 50 unit per month(over 3 month 100 to 0) to generate score of 0.4

Worsening – 10 units per month – score: 0.08

-----------------------------------

**Effect of History**
Social better – history of 1 month – score: -0.009
Social worse – history of 1 month – score: -0.045
Improving – history of 1 month – score: -0.009
Worsening – history of 1 month – score: -0.045

**Comment by pboisver** [comment]
* Reduce duplication in ach. & loss scorers (and signals?). Do we need two scorers?
* Keep pinning down final scoring and individual scorers (return to base)
* parameterized tests
* Check moderator normalization
* Where to detect history signals
* error handling for scorers (see TODO:)
