### ISSUE TITLE
# GC deployment runs slow, is disrupted often

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/precision-feedback-pipeline#312]
Testing with LeakDown tester against the deployed instance in the HITS-provided Google Cloud Kubernetes environment showed that the PFP runs quite slowly (for example, compared to a $7/mo base instance at Heroku). 

It also fails in some manner after a small number of requests and has to wait for the service to be re-established; this happens several times in a small run like the current pilot run of 60 providers. It will have a greater impact when we run a full trial.

Not sure why a typical cloud provider (Google Cloud) shows these behaviors when they are not present in other environments. 

Note: The authentication and authorization required by the HITS cloud environment may contribute to the complexity of configuration, but, when correctly configured, should not cause this behavior.

### Things to try
* Add request timing info to the response
* Try removing authentication from GKE (or try adding it to Heroku)
* Try changing resource limits at GKE (HITS has to do this)
* Nake sure the production .env is correct, correct, correct and being used

**Comment by icejag** [comment]
On discussing with john walsh for the ticket INC2376477 from HITS devops team 
Hits offered two solutions
-Change the replica count
- utilize a "/health" endpoint (for instance) rather than just "/." Then, the "/health" endpoint is designed to use less CPU and just provide an status of your application for fast api ("https://pypi.org/project/fastapi-healthcheck/")

The ticket link-https://michmed.service-now.com/sp?id=ticket&table=incident&sys_id=31f259d547263d140842a1cd416d43f1

**Comment by pboisver** [comment]
* Submit a HIT ticket to get GKE instances with twice as much memory and the next larger CPU size. (If possible)
* Reduce the number of GKE instances to 2 in test and prod (we have no clients that send multiple requests)
* Check whether the "bill" is covered by the researcher package or from the grant
* Try running a large dataset and tweaker the parameters in Heroku (and on GKE)

**Comment by pboisver** [comment]
- We can think about reducing replicas for test and prod (is 1 enough?)
- We can think about autoscaling (maybe to zero)
- Do we even need pfp.lab?
- How much more memory do we need if we add workers and/or switch to `gunicorn`? May not need more CPU...the idea is to increase CPU utilization

**Comment by pboisver** [comment]
Updated deployments with larger instances and more memory perform adequately
