### ISSUE TITLE
Trend display shows values for only last 3 months

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/precision-feedback-pipeline#328]
Bar chart shows values (numbers) for all months

Test w/ at least 4 months of data and a positive trend

**Comment by faridseifi** [comment]
![Image](https://github.com/Display-Lab/precision-feedback-pipeline/assets/44787630/d056f3d6-ef26-42cc-aa63-7b55523bafcd)



![Image](https://github.com/Display-Lab/precision-feedback-pipeline/assets/44787630/115c2110-ccfc-402b-804e-0f0cbfeaec28)

**Comment by faridseifi** [comment]
Won't do it. Three month is good for now.
