### ISSUE TITLE
Refactor candidate smasher and Thinkpudding to use new graph model

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/precision-feedback-pipeline#330]
### Motivation
We think that by replacing bitstomach we can use the underlying graph model for performance content and construction of candidates (from the base graph—CPs and message templates)

### Notes

* Will need to update Pictoralist to use terms/nodes from the new model
* Esteemer is already mostly using the new model.

**Comment by faridseifi** [comment]
These are the properties that we need for a candidates
* URIRef(SLOWMO.Candidate)
* URIRef("slowmo:acceptable_by")
* SLOWMO.RegardingMeasure
* URIRef("http://example.com/slowmo#AncestorTemplate")
PSDO.motivating_information[] (we may change it to has_motivating_information)
SLOWMO.IsAbout ? previously needed to to get comparator type but now we could get it from ancestor template
SLOWMO.name ? previously needed for outpu (message template name) but now we could get it from ancestor template
URIRef("psdo:PerformanceSummaryTextualEntity") ? previously needed for outpu (message text) but now we could get it from ancestor template
SLOWMO.RegardingComparator ? this is used in render and we need to review how it is used but now we could get it from ancestor template

Note: The start ones are needed and the others could be added for convenience

**Comment by pboisver** [comment]
#### Next

* Finish up Signal.matching_types
* Update URIRef("motivating_info") to PSDO:motivating_info
* Add Signal.matching_type() to parent returning a list with current type info. Signals (like comparison should only) override if they need to add extra type info (like comparator types) 
*
