### ISSUE TITLE
Select visual display based on preferences

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/precision-feedback-pipeline#365]
what is the default? use message template's "Default display" (check if all messages has it if not we can add it)
if preferences has values for more than one of the items, do we give weights in selecting one? No, it is binary so only one of the choices has value 1 and the rest are 0..

**Comment by faridseifi** [comment]
Branch is updated with the necessary changes to implement selection of visual display based on preferences if any, with default value being the "default display" of the template message for selected candidate.

The MPOG pilot branch needs to be updated with the changes made to include "Default display" in context and values.
