### ISSUE TITLE
Incorporate intelligence into the pipeline to combine causal pathways,templates into single file in knowledgebase

### ISSUE THREAD

**Issue by Ayshwaryajagadeesan** [Display-Lab/precision-feedback-pipeline#37]
Incorporate intelligence into the pipeline to combine causal pathways,templates into single file in knowledgebase. Test environmental variable in GCP. Also create a ticket to trigger deployment of GCP whenever there is change in the pipeline.

**Comment by icejag** [comment]
Raised a ticket in devops team to INC2203828 to test the GCP env variable.

**Comment by icejag** [comment]
Done!Check the [commit](https://github.com/Display-Lab/precision-feedback-pipeline/commit/05bc0d743108d29ac4f961726d8cbb53ec1ab55b)
