### ISSUE TITLE
[Bug] Error with uvicorn startup during local testing (Windows)

### ISSUE THREAD

**Issue by mackgalante** [Display-Lab/precision-feedback-pipeline#38]
Alrighty, so here is what I have managed to scrap together trying to solve my issues with uvicorn trying to test the pipeline locally. Going to use this as a thread to record my progress (failures) as I try and squash this thing.

Full error log from cmd prompt:

![image](https://github.com/Display-Lab/precision-feedback-pipeline/assets/133153871/caf338c8-c32d-4ecc-8b67-4cdc93f9a060)

**Comment by mackgalante** [comment]
I don't think this is an installation error, unless I need to deprecate uvicorn because of some kind of bug that made it through their team into the most current version. Potential path to resolve...

I (currently) think the smoking gun here lies in the `main.py` file, line 43:
> f3json=se.get(settings.measures).text

It seems to not like something about `measures.json` in the startup folder, but that is a huge file and checking for whatever is throwing the ValueError seems like a needle in a haystack issue. I'll try poking around in the measures file, changing strings related to what uvicorn is defining as the host

**Comment by mackgalante** [comment]
Poked around in `measures.json`, which as the title says is like 600 lines of code bringing in data about MPOG measures - nothing there that would be throwing the error.

Made some changes in the first hundred lines of code - played with @context, @id, and @type to try and see if anything in there was our culprit, no luck. Changes to strings had no effect on the error message. Changing the entire `measures.json` file to be blank did not affect error. :(

Next idea is to listen to the command prompt, and poke around in `requests_file.py` inside poetry itself. Might be able to find some help on stackoverflow for issues with this script.

**Comment by mackgalante** [comment]
Looking into the `requests_file.py` script where the error stems from I find this bad boy:
```
# Reject URLs with a hostname component
        if url_parts.netloc and url_parts.netloc != "localhost":
            raise ValueError("file: URLs with hostname components are not permitted")
```
- trying just running uvicorn from poetry with this error catcher commented out...
- doing so gives us a new fun error:

![image](https://github.com/Display-Lab/precision-feedback-pipeline/assets/133153871/42c3e92e-6f96-43e1-8a8f-252a80a38c4d)


The new offender is this lad:
```
# Try to put the path back together
# Join the drive back in, and stick os.sep in front of the path to make it absolute.
path = path_drive + os.sep + os.path.join(*path_parts)
```

Would love to try to bypass this, but this isn't error catching, we are into essential function parts of the script from the looks of it. Time to check in with stackoverflow...

**Comment by mackgalante** [comment]
Seems like someone else on github has had issues with `os.path.join` before, and they resolved it. Apparently this error gets thrown when `os.path.join` receives no arguments. See code below to check me, but seems then that `path_parts` is empty...

![image](https://github.com/Display-Lab/precision-feedback-pipeline/assets/133153871/c6c1f7ed-a1df-44fd-b9f9-f6996a95cad9)


Now trying to find where `path_parts` variable gets defined, which is in line 44:
> path_parts = [unquote(p) for p in url_parts.path.split("/")]

and now, of course, `url_parts` is defined as `url_parts = urlparse(request.url)` from where the script parses our URL in line 30, which is of course above where I did my little bypass. It seems to me that we are trying to pass this script a URL that it really, really does not like. It also seems apparent that my little hotwire/bypass attempt has caused errors down the line as I let `url_parts` get defined as something that the script isn't happy handling.

I love debugging.

**Comment by mackgalante** [comment]
Going back to the drawing board here. I'm thinking that this script is breaking due to a path error, which stems from a URL, however I don't know where we are defining what URL we want this thing to try...

Going to try running the pipeline from inside the main python folder that I installed, which is going to be annoying from a directory pathing stance on my end, but might help? If this solves things I am going to be very upset with myself for thinking I knew what I was doing earlier, but it shouldn't change anything about what is going on - python and poetry should function well enough the way I have my directories setup, from my understanding.

- Good news and bad, good news is running the PFP from inside `Python310` folder changes nothing - the ValueError is identical. Bad news, the ValueError is identical.

**Comment by mackgalante** [comment]
Thought about how to best squash this over the weekend, and it looks like I found a way to get the pipeline working with windows:

We knew that there were errors with the URLs used in the startup process of `main.py` - after some review we can see that `settings.measures` URL points to a file path instead of a proper URL. We can however make the `settings` class use filepaths instead of file URLs, which lets everything run.

I am pasting a code snippet below of the changes I made to `main.py` which lets it run on windows:



![Image](https://github.com/Display-Lab/precision-feedback-pipeline/assets/133153871/80619316-8244-45b9-a853-13fa01b7e4e6)

**Comment by mackgalante** [comment]
I have copied the changed code below for posterity, I'll close the issue with this and get to testing!

## Updated code block ##
Modified to read JSON files directly instead of using `requests.get()` since running locally
Using `with open()` to open JSON files, then loading with `json.load()` to parse into py objects:
>        with open(settings.pathways, "r") as f:
>            f2json = json.load(f)
>            
>        with open(settings.measures, "r") as f:
>            f3json = json.load(f)
>            
>        with open(settings.templates, "r") as f:
>            f4json = json.load(f)
>            
>        causal_pathways = read_graph(json.dumps(f2json))
>        templates = read_graph(json.dumps(f4json))
>
>        print("startup is complete")

**Comment by pboisver** [comment]
Here are examples (from chatgpt) of typical file paths on Windows in `file://` URI scheme format. These should be usable with ENV variables. Tests to follow.

----

The "file://" URI scheme is used to specify the location of a file on a local file system. Here are some examples of "file://" URIs in Windows:

Absolute Path:

file:///C:/path/to/file.txt: Specifies the file "file.txt" located at "C:\path\to" on the C: drive.
Relative Path:

file:///path/to/file.txt: Specifies the file "file.txt" located at "C:\current\directory\path\to" on the C: drive. This assumes that the current working directory is "C:\current\directory".
UNC Path:

file:////server/share/path/to/file.txt: Specifies the file "file.txt" located at "\server\share\path\to". UNC paths are used for network file access.
Spaces in Path:

file:///C:/path%20with%20spaces/file.txt: Specifies the file "file.txt" located at "C:\path with spaces". Spaces are encoded as "%20" in URIs.
Special Characters in Path:

file:///C:/path%26file/file%23.txt: Specifies the file "file#.txt" located at "C:\path&file". Special characters such as "&" and "#" are encoded in URIs.
Remember that when working with file URIs, you need to use the correct file path syntax for the operating system you are using. In Windows, backslashes () are typically used as directory separators in file paths.
