### ISSUE TITLE
Remove unused imports (everywhere)

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/precision-feedback-pipeline#4]
for example, in thinkpudding.py:

```python
import pandas as pd
from rdflib import Graph, Literal, Namespace, URIRef,BNode
from rdflib.collection import Collection
from rdflib.namespace import FOAF, RDF, RDFS, SKOS, XSD
from rdflib.serializer import Serializer
from rdfpandas.graph import to_dataframe
from SPARQLWrapper import XML, SPARQLWrapper
import collections
```

**Comment by icejag** [comment]
I removed all unused imports in each and every python code using autoflake extension in visual studio code. I tested the code after removing the unused imports and found the codebase working fine. Please check the commit [commit1](https://github.com/Display-Lab/precision-feedback-pipeline/commit/a7d4c2c751ca15bae3f9d649a08ffbb187046ec6) for reference.
