### ISSUE TITLE
[Bug] Measure name requires RDFlib counterpart

### ISSUE THREAD

**Issue by mackgalante** [Display-Lab/precision-feedback-pipeline#45]
When the pipeline receives a post request wherein the only measure in the performance data is not consistent with the measures listed in `measures.json`, we receive a 500 Internal Service Error. Console output below:

> Local\pypoetry\Cache\virtualenvs\pfp-api-boqbVOT5-py3.10\lib\site-packages\rdflib\graph.py", line 534, in add 
> AssertionError: Object None must be an rdflib term

Found on Windows, local testing
Reproducible in local, heroku

_Notes:_
We expect for nearly every instance that MPOG will send auto-generated data logs that are inherently free of errors like a typo - however, it may be worthwhile to have the pipeline be able to handle the measure name not matching the RDFlibrary and send an informative message back to MPOG so they are aware of what needs to be corrected.

**Comment by mackgalante** [comment]
Error persistant, can generate repeatedly from processing Fahad or Gaile input messages

**Comment by mackgalante** [comment]
Received consistently on repoTest from Leakdown Tester (see above)

**Comment by mackgalante** [comment]
Still present when testing persona datasets... Will try editing measures.json to correct issue myself

**Comment by mackgalante** [comment]
[Knowledgebase main updated ](https://github.com/Display-Lab/knowledge-base/commit/825cf0532305f9bc4ad24360c5b37ddffb4966b0), verified consistent implementation of the new measures for Fahad and Gaile personas, added new entries to measures.json

**Comment by mackgalante** [comment]
Tested RDFlib bug fix works on local pipeline instance, will push changes to branch for team approval

**Comment by icejag** [comment]
what? please clarify. First of all it was'nt even a bug to be fixed. Please use your time usefully.

**Comment by mackgalante** [comment]
Patch should be implemented, all set to resolve issue as long as pipeline is staying up-to-date with the knowledgebase!
