### ISSUE TITLE
Create line chart

### ISSUE THREAD

**Issue by anjanadeep** [Display-Lab/precision-feedback-pipeline#49]
create a line chart without a goal line. 

Need to decide how to choose the number of months. 

Need to decide how to include comparators dynamically. 

https://docs.google.com/spreadsheets/d/1h81ZmTqMWvWDcpLIr5IFW-AAmEiqQAPB4ZtyQtY87HQ/edit#gid=1418181108

**Comment by mackgalante** [comment]
Functionality is included with latest pictoralist, still need some architecture decisions about how we want to implement the ability for a user to change these on the fly, and if not, how we have them changed at an organizational level.

But, again, code is now here for:
- adding/removing goal line (smoke tested)
- changing number of months in display (tested (ten cases, edges))
- dynamic comparators are the core of the new pictoralist, thoroughly tested

Todo: Decide how we want end users to influence the control keys for display_timeframe, generate_goal_line, and potentially influence selected_measure/comparator_type
