### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by zachll** [Display-Lab/precision-feedback-pipeline#6]
Rename the pfp_API repository to precision-feedback-pipeline

Remove the pfpAPI and pfp-api repositories to avoid confusion with similar names.

**Comment by icejag** [comment]
I renamed the pfp_API repository to precision-feedback-pipeline.Please check [precision-feedback-pipeline](https://github.com/Display-Lab/precision-feedback-pipeline)
I removed the pfpAPI and pfp-api repositories to avoid confusion with similar names.
