### ISSUE TITLE
Pictoralist needs to handle variable data for displays

### ISSUE THREAD

**Issue by zachll** [Display-Lab/precision-feedback-pipeline#63]
Pictoralist should display any valid message that it receives from Esteemer

 - for bar charts and line charts, can we dynamically choose the number of months, based on the length monotonic trends?

**Comment by zachll** [comment]
This will also be relevant to problems resulting from too few months of data (<3) being available to make a chart that is useful

**Comment by zachll** [comment]
Pictoralist may need to create a message with a chart using only 2 or 3 time intervals, which may not be very readable in a chart.

decide how to handle charts when there are few time intervals

**Comment by zachll** [comment]
Esteemer needs to consider when a chart may be inappropriate for Pictoralist:

missing data / gaps
handling durations of < 3 time intervals
choosing based on individual or group preferences

**Comment by mackgalante** [comment]
Commit https://github.com/Display-Lab/precision-feedback-pipeline/pull/113/commits/0c3c26e11d7477d112d453e685973886d4b80565 in pictoralist cleanup, addresses <3 month issue, data gaps, and sets infrastructure for restricting the number of months to display on a dynamic basis.
