### ISSUE TITLE
[Bug] Goal comparators are evaluated as social comparators

### ISSUE THREAD

**Issue by mackgalante** [Display-Lab/precision-feedback-pipeline#64]
When testing social worse causal pathway, social better is deemed acceptable when the only comparator lower than the performance level is `MPOG_goal`

See below for input message file, or see `social_worse_cptest.json`

With the input message's data, there should be no way for social better to be an acceptable causal pathway unless the pipeline treats the MPOG_goal value as a social comparator.

Found with Leakdown Tester, will provide input/output to replicate, and will try to replicate with Postman

**Comment by mackgalante** [comment]
Input file:

{
    "@context": {
      "@vocab": "http://schema.org/",
      "slowmo": "http://example.com/slowmo#",
      "csvw": "http://www.w3.org/ns/csvw#",
      "dc": "http://purl.org/dc/terms/",
      "psdo": "http://purl.obolibrary.org/obo/",
      "slowmo:Measure": "http://example.com/slowmo#Measure",
      "slowmo:IsAboutPerformer": "http://example.com/slowmo#IsAboutPerformer",
      "slowmo:ColumnUse": "http://example.com/slowmo#ColumnUse",
      "slowmo:IsAboutTemplate": "http://example.com/slowmo#IsAboutTemplate",
      "slowmo:spek": "http://example.com/slowmo#spek",
      "slowmo:IsAboutCausalPathway": "http://example.com/slowmo#IsAboutCausalPathway",
      "slowmo:IsAboutOrganization": "http://example.com/slowmo#IsAboutOrganization",
      "slowmo:IsAboutMeasure": "http://example.com/slowmo#IsAboutMeasure",
      "slowmo:InputTable": "http://example.com/slowmo#InputTable",
      "slowmo:WithComparator": "http://example.com/slowmo#WithComparator",
      "has_part": "http://purl.obolibrary.org/obo/bfo#BFO_0000051",
      "has_disposition": "http://purl.obolibrary.org/obo/RO_0000091"
    },
  "Performance_data":[
      ["staff_number","measure","month","passed_count","flagged_count","denominator","peer_average_comparator","peer_75th_percentile_benchmark","peer_90th_percentile_benchmark","MPOG_goal"],
      [7,"GLU01","2023-01-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-02-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-03-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-04-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-05-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-06-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-07-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-08-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-09-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-10-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-11-01",45,55,100,50,99,99,1],
      [7,"GLU01","2023-12-01",45,55,100,50,99,99,1]
    ],
  "History":{
  },
  "Preferences":{
      "Utilities": {
      "Message_Format": 
        {
          "1": "0.0",
          "2": "0.1",
          "16": "7.5",
          "24": "9.4",
          "18": "11.3",
          "11": "13.2",
          "22": "15.1" ,
          "14": "22.6" ,
          "21": "62.3" ,
          "5":"0.2",
          "15":"4.0",
          "4":"0.9"
        },
      "Display_Format":
        {
          "short_sentence_with_no_chart": "0.0",
          "bar": "37.0",
          "line": "0.0"
        }
    }
  }
}

**Comment by mackgalante** [comment]
Output (Leakdown Tester V1.6.0 indev):
```text
Testing input_message file for causal pathway 'SOCIAL WORSE'
Thread 1, Test 2, Request 9:
    Response recieved in 1.911 seconds.

CAUSAL PATHWAY VALIDATION:      FAIL
Specified Pathway:      social worse
Accepted Pathway:       social better
```

**Comment by mackgalante** [comment]
Bug not related to error with just one causal pathway, confirmed present in goal_gain as well.

Verified that the message LDT is sending the API contains the expected performance data, and is not an artifact of my VSCode environment.

Additionally, it looks like social gain is being tripped by any increase of performance that is above a social comparator, otherwise social gain would not be an acceptable candidate. Can make a separate bug issue for this in the morning and test more thoroughly. 

Input:
```json
{
    "@context": {
      "@vocab": "http://schema.org/",
      "slowmo": "http://example.com/slowmo#",
      "csvw": "http://www.w3.org/ns/csvw#",
      "dc": "http://purl.org/dc/terms/",
      "psdo": "http://purl.obolibrary.org/obo/",
      "slowmo:Measure": "http://example.com/slowmo#Measure",
      "slowmo:IsAboutPerformer": "http://example.com/slowmo#IsAboutPerformer",
      "slowmo:ColumnUse": "http://example.com/slowmo#ColumnUse",
      "slowmo:IsAboutTemplate": "http://example.com/slowmo#IsAboutTemplate",
      "slowmo:spek": "http://example.com/slowmo#spek",
      "slowmo:IsAboutCausalPathway": "http://example.com/slowmo#IsAboutCausalPathway",
      "slowmo:IsAboutOrganization": "http://example.com/slowmo#IsAboutOrganization",
      "slowmo:IsAboutMeasure": "http://example.com/slowmo#IsAboutMeasure",
      "slowmo:InputTable": "http://example.com/slowmo#InputTable",
      "slowmo:WithComparator": "http://example.com/slowmo#WithComparator",
      "has_part": "http://purl.obolibrary.org/obo/bfo#BFO_0000051",
      "has_disposition": "http://purl.obolibrary.org/obo/RO_0000091"
    },
  "Performance_data":[
      ["staff_number","measure","month","passed_count","flagged_count","denominator","peer_average_comparator","peer_75th_percentile_benchmark","peer_90th_percentile_benchmark","MPOG_goal"],
      [7,"TOC01","2023-01-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-02-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-03-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-04-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-05-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-06-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-07-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-08-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-09-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-10-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-11-01",89,11,100,1,1,1,90],
      [7,"TOC01","2023-12-01",91,9,100,1,1,1,90]
    ],
  "History":{
  },
  "Preferences":{
      "Utilities": {
      "Message_Format": 
        {
          "1": "0.0",
          "2": "0.1",
          "16": "7.5",
          "24": "9.4",
          "18": "11.3",
          "11": "13.2",
          "22": "15.1" ,
          "14": "22.6" ,
          "21": "62.3" ,
          "5":"0.2",
          "15":"4.0",
          "4":"0.9"
        },
      "Display_Format":
        {
          "short_sentence_with_no_chart": "0.0",
          "bar": "37.0",
          "line": "0.0"
        }
    }
  }
}
```
Output (LDT V1.6.0 indev):
```text
(.venv) mack@Macks-MacBook-Pro wip % /Users/mack/Code/wip/.venv/bin/python /Users/mack/Code/wip/precision-feedback-pipeline/LeakdownTester/LDT.py --target local  --causeVal --tests 10 --pathway goal_gain   

                Welcome to the Leakdown Tester, Version 1.6.0!
Reading one JSON file from knowledge-base folder 'Causal Pathway Test Suite'...
Sending 10 total POST requests...
Sending POST request(s) to API at 'http://127.0.0.1:8000/createprecisionfeedback/'...


Testing input_message file for causal pathway 'GOAL GAIN'
Thread 1, Test 1, Request 1:
    Response recieved in 1.970 seconds.

CAUSAL PATHWAY VALIDATION:      FAIL
Specified Pathway:      goal gain
Accepted Pathway:       social gain


Testing input_message file for causal pathway 'GOAL GAIN'
Thread 1, Test 2, Request 1:
    Response recieved in 2.659 seconds.

CAUSAL PATHWAY VALIDATION:      FAIL
Specified Pathway:      goal gain
Accepted Pathway:       social better


Testing input_message file for causal pathway 'GOAL GAIN'
Thread 1, Test 3, Request 1:
    Response recieved in 1.992 seconds.

CAUSAL PATHWAY VALIDATION:      FAIL
Specified Pathway:      goal gain
Accepted Pathway:       social gain


Testing input_message file for causal pathway 'GOAL GAIN'
Thread 1, Test 4, Request 1:
    Response recieved in 2.130 seconds.

CAUSAL PATHWAY VALIDATION:      FAIL
Specified Pathway:      goal gain
Accepted Pathway:       social gain


Testing input_message file for causal pathway 'GOAL GAIN'
Thread 1, Test 5, Request 1:
    Response recieved in 1.929 seconds.

CAUSAL PATHWAY VALIDATION:      PASS
Specified Pathway:      goal gain
Accepted Pathway:       goal gain


Testing input_message file for causal pathway 'GOAL GAIN'
Thread 1, Test 6, Request 1:
    Response recieved in 2.451 seconds.

CAUSAL PATHWAY VALIDATION:      FAIL
Specified Pathway:      goal gain
Accepted Pathway:       improving


Testing input_message file for causal pathway 'GOAL GAIN'
Thread 1, Test 7, Request 1:
    Response recieved in 2.396 seconds.

CAUSAL PATHWAY VALIDATION:      FAIL
Specified Pathway:      goal gain
Accepted Pathway:       social gain


Testing input_message file for causal pathway 'GOAL GAIN'
Thread 1, Test 8, Request 1:
    Response recieved in 2.322 seconds.

CAUSAL PATHWAY VALIDATION:      FAIL
Specified Pathway:      goal gain
Accepted Pathway:       social better


Testing input_message file for causal pathway 'GOAL GAIN'
Thread 1, Test 9, Request 1:
    Response recieved in 2.064 seconds.

CAUSAL PATHWAY VALIDATION:      PASS
Specified Pathway:      goal gain
Accepted Pathway:       goal gain


Testing input_message file for causal pathway 'GOAL GAIN'
Thread 1, Test 10, Request 1:
    Response recieved in 2.260 seconds.

CAUSAL PATHWAY VALIDATION:      FAIL
Specified Pathway:      goal gain
Accepted Pathway:       social better


                Leakdown test complete.
```

**Comment by icejag** [comment]
I am not able to recreate the issue number 2. The out-put the pipeline throws is
{
  "staff_number": 7,
  "selected_candidate": {
    "message_template": "https://repo.metadatacenter.org/template-instances/5c49f6e6-b95f-4eb9-baa9-dac580e33e20",
    "display": "line graph",
    "measure": "TOC01",
    "acceptable_by": [
      "Social better",
      "Social Gain",
      "Improving"
    ]
  }, and it is pretty consistent to what is expected. If you were able to recreate the issue please keep me posted.

**Comment by mackgalante** [comment]
Tested Goal Loss, received erroneous acceptable w/ pathway social loss, not goal loss accepted.

Input:

```json
  "Performance_data":[
      ["staff_number","measure","month","passed_count","flagged_count","denominator","peer_average_comparator","peer_75th_percentile_benchmark","peer_90th_percentile_benchmark","MPOG_goal"],
      [7,"SUS04","2023-01-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-02-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-03-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-04-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-05-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-06-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-07-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-08-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-09-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-10-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-11-01",15,85,100,100,100,100,11],
      [7,"SUS04","2023-12-01",10,90,100,100,100,100,11]
    ],
  "History":{
  },
```



Output:
```bash
Testing input_message file for causal pathway 'GOAL LOSS'
 Thread 1, Test 1, Request 3:   Response recieved in 0.913 seconds.
 API response contains keys:
        Staff ID Number:        7
        Display Type:           Text-only
        Measure:                SUS04
        Acceptable By:          ['social loss', 'Social Worse', 'Worsening']
        Abbreviated Message:    Your performance dropped below the peer average this month for the measure [Measure n
        Comparison Value:       0.9
```


Context:
- Social loss should not be present, since all social comparators are all at 100
- Goal loss should instead be present in acceptable array
    - Thinking goal comparator being treated as if it were a social comparator
- Worsening, social worse are acceptable pathways, correct in output

**Comment by icejag** [comment]
Done and dusted.Check the [link](https://github.com/Display-Lab/precision-feedback-pipeline/commit/2f9f6866a4b35409aeabe460484e94899ebe5e5d)
