### ISSUE TITLE
Add "using with a virtual environment" notes to readme

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/precision-feedback-pipeline#7]
Anyone checking out the pfpAPI should get precisely the dependencies and versions necessary so a virtual environment will keep things from getting mixed up. It also helps ensure that no systems-installed packages are being relied on when developing.

The combination of `pyenv` and `poetry` will work. See https://python-poetry.org/docs/managing-environments/ for more info.

**Comment by icejag** [comment]
I added the instructions into read-me document. Please [check](https://github.com/Display-Lab/precision-feedback-pipeline)
