### ISSUE TITLE
[Bug] Export variables (measures, pathways, templates) not allowing remote resources

### ISSUE THREAD

**Issue by mackgalante** [Display-Lab/precision-feedback-pipeline#75]
In efforts to remove pipeline's dependency on local startup files which are mirrors of the knowledgebase, encountered issues with being able to set environmental variables that allow the pipeline to pull in URIs. Something about the way that the export variables are being used by the pipeline has been broken, and does not allow URIs to supersede the startup version of the measures, pathways, and templates.

Tested in person on 9/19, demonstrated that URIs are not being used when set as export variables :(

As far as criticality, this is necessary for the pilot if the pilot is to be hosted on GCP with limited local storage. Need to be able to allow env vars to set URI content sources, then can build CLI tools to test routing and configurations outside of the startup script.

**Comment by 00hchung99** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pilot progress](https://trello.com/c/69JUSCPQ/2-pilot-progress)

**Comment by mackgalante** [comment]
Patch is live on the following branch of the pipeline repo: 
https://github.com/Display-Lab/precision-feedback-pipeline/commit/afee5b769644e9f312d2ece6047187aab1621abe

See changelog for descriptive details on the patch

**Comment by mackgalante** [comment]
Resolved, closing
