### ISSUE TITLE
Debug mode should be set via flag

### ISSUE THREAD

**Issue by pboisver** [Display-Lab/precision-feedback-pipeline#8]
A command line flag and/or environment variable should work. This is part of moving to a stable production mode, where the base graph is loaded/constructed once from the knowledge base artifacts, and then each request is processed using a "request-scoped" performer graph. Debugging should be set for the pipeline, not the request. 

Also debugging should generally provide info from the performer graph

sample code:
```python
import logging
logging.basicConfig(
    level=os.environ.get('LOGLEVEL', 'INFO').upper()
)
```

See #118 for followup
(resolves #118)

**Comment by mackgalante** [comment]
Having trouble getting a handler added to the fastAPI app. Will include the code block I tried to set up the handler with:
```python
### Logging module setup
# settings.log_level must contain a string like 'INFO' or 'DEBUG'
log_level = getattr(logging, settings.log_level, logging.INFO)
logging.basicConfig(level=log_level)
main_log = logging.StreamHandler()
main_log.setLevel(log_level)
root_logger = logging.getLogger()
root_logger.addHandler(main_log)
```

**Comment by mackgalante** [comment]
Importing task list from pictoralist infrastructure issue:

- [ ] Debug flag as env var -> interface with logging module (#8) 
    - [ ] Implement logging alongside FastAPI app (likely a can of worms here)
    - [ ] Add debug, info, and warning/critical logging statements where appropriate
    - [x] Implement info level spec by env var

**Comment by mackgalante** [comment]
Implemented logging with loguru module, much easier to work with and more powerful than default logging module.

See documentation here:
https://github.com/Delgan/loguru/blob/master/README.rst

Dependencies updated in the branch generated on this issue, ready for review
